import type { Metadata } from "next";
import "./globals.css";
import MobileNavBar from "@/components/MobileNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="bg-white min-h-screen w-full flex flex-col">
        <header className="py-2 text-center font-bold border-b">test</header>
        <div className="pb-20 m-4">{children}</div>
        <MobileNavBar />
      </body>
    </html>
  );
}
